//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.Prompts.ValidateDateTimeWaterfall.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidateDateTimeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidateDateTimeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.Prompts.ValidateDateTimeWaterfall.Resources.ValidateDateTimeStri" +
                            "ngs", typeof(ValidateDateTimeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course. When would you be arriving?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_ARRIVAL_1 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_ARRIVAL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure. When would you want to checkin?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_ARRIVAL_2 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_ARRIVAL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, let&apos;s do that. When do you want to arrive?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_ARRIVAL_3 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_ARRIVAL_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure! When would you be arriving?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_ARRIVAL_4 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_ARRIVAL_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, let&apos;s update that. When do you want to arrive?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_ARRIVAL_5 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_ARRIVAL_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, let&apos;s change that. When would you checkin?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_ARRIVAL_6 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_ARRIVAL_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure! When would you be leaving?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_DEPARTURE_1 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_DEPARTURE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it, when would you leave?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_DEPARTURE_2 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_DEPARTURE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure. When would you want to leave?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_DEPARTURE_3 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_DEPARTURE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, let&apos;s change that. When would you checkout?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_DEPARTURE_4 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_DEPARTURE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, let&apos;s update that; When do you want to leave?.
        /// </summary>
        public static string MATCHED_INTENT_NO_ENTITY_DEPARTURE_5 {
            get {
                return ResourceManager.GetString("MATCHED_INTENT_NO_ENTITY_DEPARTURE_5", resourceCulture);
            }
        }
    }
}
