//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.Prompts.DepartureDate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DepartureDateStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DepartureDateStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.Prompts.DepartureDate.Resources.DepartureDateStrings", typeof(DepartureDateStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On what day would you like to checkout?.
        /// </summary>
        public static string DEPARTURE_DATE_PROMPT_1 {
            get {
                return ResourceManager.GetString("DEPARTURE_DATE_PROMPT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On what day would you like to leave?.
        /// </summary>
        public static string DEPARTURE_DATE_PROMPT_2 {
            get {
                return ResourceManager.GetString("DEPARTURE_DATE_PROMPT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you be leaving us?.
        /// </summary>
        public static string DEPARTURE_DATE_PROMPT_3 {
            get {
                return ResourceManager.GetString("DEPARTURE_DATE_PROMPT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you checkout?.
        /// </summary>
        public static string DEPARTURE_DATE_PROMPT_4 {
            get {
                return ResourceManager.GetString("DEPARTURE_DATE_PROMPT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you like to checkout?.
        /// </summary>
        public static string DEPARTURE_DATE_PROMPT_5 {
            get {
                return ResourceManager.GetString("DEPARTURE_DATE_PROMPT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you be leaving?.
        /// </summary>
        public static string DEPARTURE_DATE_PROMPT_6 {
            get {
                return ResourceManager.GetString("DEPARTURE_DATE_PROMPT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you like to checkout?.
        /// </summary>
        public static string DEPARTURE_DATE_PROMPT_7 {
            get {
                return ResourceManager.GetString("DEPARTURE_DATE_PROMPT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it, you want to checkout on {0}..
        /// </summary>
        public static string HAVE_DEPARTURE_DATE_1 {
            get {
                return ResourceManager.GetString("HAVE_DEPARTURE_DATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it, checking out on {0} 👊.
        /// </summary>
        public static string HAVE_DEPARTURE_DATE_2 {
            get {
                return ResourceManager.GetString("HAVE_DEPARTURE_DATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, leaving on {0}..
        /// </summary>
        public static string HAVE_DEPARTURE_DATE_3 {
            get {
                return ResourceManager.GetString("HAVE_DEPARTURE_DATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would leave on {0}..
        /// </summary>
        public static string HAVE_DEPARTURE_DATE_4 {
            get {
                return ResourceManager.GetString("HAVE_DEPARTURE_DATE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would be checking out on {0}..
        /// </summary>
        public static string HAVE_DEPARTURE_DATE_5 {
            get {
                return ResourceManager.GetString("HAVE_DEPARTURE_DATE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, I updated your checkout date to {0}..
        /// </summary>
        public static string HAVE_UPDATED_DEPARTURE_DATE_1 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_DEPARTURE_DATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, I changed your checkout date to {0} 😉.
        /// </summary>
        public static string HAVE_UPDATED_DEPARTURE_DATE_2 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_DEPARTURE_DATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, I updated the checkout date to {0}..
        /// </summary>
        public static string HAVE_UPDATED_DEPARTURE_DATE_3 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_DEPARTURE_DATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated checkout date to {0}..
        /// </summary>
        public static string HAVE_UPDATED_DEPARTURE_DATE_4 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_DEPARTURE_DATE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated checkout date to {0} 😉.
        /// </summary>
        public static string HAVE_UPDATED_DEPARTURE_DATE_5 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_DEPARTURE_DATE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed checkout date to {0}..
        /// </summary>
        public static string HAVE_UPDATED_DEPARTURE_DATE_6 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_DEPARTURE_DATE_6", resourceCulture);
            }
        }
    }
}
