//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.Main.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.Main.Resources.MainStrings", typeof(MainStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string CALL_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CALL_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our number 📱.
        /// </summary>
        public static string CALL_CARD_TITLE {
            get {
                return ResourceManager.GetString("CALL_CARD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You wouldn&apos;t be talking to me, but give us a call and my colleagues would be glad to help 🤙.
        /// </summary>
        public static string CALL_REPLY_TEXT {
            get {
                return ResourceManager.GetString("CALL_REPLY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, let&apos;s start over..
        /// </summary>
        public static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What else can I help you with?.
        /// </summary>
        public static string COMPLETED {
            get {
                return ResourceManager.GetString("COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I&apos;m not able to help with that..
        /// </summary>
        public static string CONFUSED {
            get {
                return ResourceManager.GetString("CONFUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to book a room..
        /// </summary>
        public static string CONTEXT_TEXT_BOOK_A_ROOM {
            get {
                return ResourceManager.GetString("CONTEXT_TEXT_BOOK_A_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could I call you?.
        /// </summary>
        public static string CONTEXT_TEXT_CALL {
            get {
                return ResourceManager.GetString("CONTEXT_TEXT_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could I call you?.
        /// </summary>
        public static string CONTEXT_TEXT_CALL_US {
            get {
                return ResourceManager.GetString("CONTEXT_TEXT_CALL_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need directions to your hotel..
        /// </summary>
        public static string CONTEXT_TEXT_DIRECTIONS {
            get {
                return ResourceManager.GetString("CONTEXT_TEXT_DIRECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, it looks like something went wrong..
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FDS {
            get {
                return ResourceManager.GetString("FDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GETTING_STARTED_INTRO {
            get {
                return ResourceManager.GetString("GETTING_STARTED_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need anything else, just ask!.
        /// </summary>
        public static string GREETING_MORE {
            get {
                return ResourceManager.GetString("GREETING_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started 👊.
        /// </summary>
        public static string GREETING_PROMPT_FOR_ACTION {
            get {
                return ResourceManager.GetString("GREETING_PROMPT_FOR_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, I&apos;m the new virtual front desk clerk for Starhotel 🏨 ! Management hired me to help you book a room or answer any questions you might have 😉.
        /// </summary>
        public static string GREETING_WITH_NAME {
            get {
                return ResourceManager.GetString("GREETING_WITH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can help you book a room or answer questions..
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tel: +15 105 551 234.
        /// </summary>
        public static string HOTEL_NUMBER {
            get {
                return ResourceManager.GetString("HOTEL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking overview.
        /// </summary>
        public static string QUICK_REPLY_BUTTON_BOOKING_OVERVIEW {
            get {
                return ResourceManager.GetString("QUICK_REPLY_BUTTON_BOOKING_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string QUICK_REPLY_BUTTON_CALL {
            get {
                return ResourceManager.GetString("QUICK_REPLY_BUTTON_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm booking.
        /// </summary>
        public static string QUICK_REPLY_BUTTON_CONFIRM_BOOKING {
            get {
                return ResourceManager.GetString("QUICK_REPLY_BUTTON_CONFIRM_BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string QUICK_REPLY_BUTTON_DIRECTION {
            get {
                return ResourceManager.GetString("QUICK_REPLY_BUTTON_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a room.
        /// </summary>
        public static string QUICK_REPLY_BUTTON_FIND_A_ROOM {
            get {
                return ResourceManager.GetString("QUICK_REPLY_BUTTON_FIND_A_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can you do?.
        /// </summary>
        public static string QUICK_REPLY_BUTTON_WHAT_CAN_YOU_DO {
            get {
                return ResourceManager.GetString("QUICK_REPLY_BUTTON_WHAT_CAN_YOU_DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What else can I help you with?.
        /// </summary>
        public static string RANDOM_CONTINUE_1 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I help? 👊.
        /// </summary>
        public static string RANDOM_CONTINUE_2 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glad to help. Anything else? 😃.
        /// </summary>
        public static string RANDOM_CONTINUE_3 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anything else? .
        /// </summary>
        public static string RANDOM_CONTINUE_4 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do next?.
        /// </summary>
        public static string RANDOM_CONTINUE_5 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need anything else?.
        /// </summary>
        public static string RANDOM_CONTINUE_6 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any more questions about our hotel or services?.
        /// </summary>
        public static string RANDOM_CONTINUE_7 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need anything else? 😄.
        /// </summary>
        public static string RANDOM_CONTINUE_8 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy to help 😁 Anything else?.
        /// </summary>
        public static string RANDOM_CONTINUE_9 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can understand things like &quot;find me a room on april 15&quot; or &quot;show me my booked rooms&quot;. Go ahead try it out 😉.
        /// </summary>
        public static string WHAT_CAN_YOU_DO_NLU {
            get {
                return ResourceManager.GetString("WHAT_CAN_YOU_DO_NLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I try to keep things short by providing you with buttons but I&apos;m pretty smart 🤓.
        /// </summary>
        public static string WHAT_CAN_YOU_DO_SMART {
            get {
                return ResourceManager.GetString("WHAT_CAN_YOU_DO_SMART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My purpose is to assist you in booking a room with us. I can also answer any general questions you might have about our hotel. .
        /// </summary>
        public static string WHAT_CAN_YOU_DO_TASKS {
            get {
                return ResourceManager.GetString("WHAT_CAN_YOU_DO_TASKS", resourceCulture);
            }
        }
    }
}
