//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.RoomOverview.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoomOverviewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoomOverviewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.RoomOverview.Resources.RoomOverviewStrings", typeof(RoomOverviewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap confirm to confirm your booking with us or add another room. .
        /// </summary>
        public static string CONTINUE_OR_ADD_MORE_ROOMS {
            get {
                return ResourceManager.GetString("CONTINUE_OR_ADD_MORE_ROOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any rooms yet, start with adding a new room to your order. .
        /// </summary>
        public static string NO_SELECTED_ROOMS {
            get {
                return ResourceManager.GetString("NO_SELECTED_ROOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I canceled your booking for you. Check your e-mail for more information. .
        /// </summary>
        public static string NOT_SUPPORTED_YET {
            get {
                return ResourceManager.GetString("NOT_SUPPORTED_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for booking with us. Here are your booked rooms..
        /// </summary>
        public static string PAYMENTCONFIRMED_ROOMS_TEXT {
            get {
                return ResourceManager.GetString("PAYMENTCONFIRMED_ROOMS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t understand. You can proceed to payment by tapping confirm in the card. .
        /// </summary>
        public static string REPROMPT_UNCONFIRMED {
            get {
                return ResourceManager.GetString("REPROMPT_UNCONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I added that room to your order 👌.
        /// </summary>
        public static string ROOM_ADDED {
            get {
                return ResourceManager.GetString("ROOM_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I can&apos;t remove that room for your order. Maybe you tapped remove in an expired booking order 🤔.
        /// </summary>
        public static string ROOM_CANNOT_BE_REMOVED {
            get {
                return ResourceManager.GetString("ROOM_CANNOT_BE_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current booking overview.
        /// </summary>
        public static string ROOM_OVERVIEW_HEROCARD_TEXT {
            get {
                return ResourceManager.GetString("ROOM_OVERVIEW_HEROCARD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I removed that room from your order 👍.
        /// </summary>
        public static string ROOM_REMOVED {
            get {
                return ResourceManager.GetString("ROOM_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is still unconfirmed, please confirm or cancel your order. .
        /// </summary>
        public static string UNCONFIRMED_PAYMENT_CONFIRM_OR_CANCEL {
            get {
                return ResourceManager.GetString("UNCONFIRMED_PAYMENT_CONFIRM_OR_CANCEL", resourceCulture);
            }
        }
    }
}
