//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.FetchAvailableRooms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FetchAvailableRoomsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FetchAvailableRoomsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.FetchAvailableRooms.Resources.FetchAvailableRoomsStrings", typeof(FetchAvailableRoomsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you arrive?.
        /// </summary>
        public static string ARRIVALDATE_PROMPT {
            get {
                return ResourceManager.GetString("ARRIVALDATE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your email?.
        /// </summary>
        public static string EMAIL_PROMPT {
            get {
                return ResourceManager.GetString("EMAIL_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for booking with us. To enter payment follow this link:.
        /// </summary>
        public static string FINISHEDBOOKAROOM {
            get {
                return ResourceManager.GetString("FINISHEDBOOKAROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, you would like to arrive on {0}..
        /// </summary>
        public static string HAVE_ARRIVALDATE {
            get {
                return ResourceManager.GetString("HAVE_ARRIVALDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it, I&apos;ve added {0} as your primary contact address..
        /// </summary>
        public static string HAVE_EMAIL {
            get {
                return ResourceManager.GetString("HAVE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving at {0}..
        /// </summary>
        public static string HAVE_LEAVINGDATE {
            get {
                return ResourceManager.GetString("HAVE_LEAVINGDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are bringing {0} people..
        /// </summary>
        public static string HAVE_NUMBEROFPEOPLE {
            get {
                return ResourceManager.GetString("HAVE_NUMBEROFPEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can book a room by providing me the information I need. You can also update previous set values, just ask me..
        /// </summary>
        public static string HELP_MESSAGE {
            get {
                return ResourceManager.GetString("HELP_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry you cannot book a room in the past. .
        /// </summary>
        public static string INCORRECT_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To help you book a room I will need some information from you. Let&apos;s start. .
        /// </summary>
        public static string INTRODUCTION {
            get {
                return ResourceManager.GetString("INTRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you be leaving?.
        /// </summary>
        public static string LEAVINGDATE_PROMPT {
            get {
                return ResourceManager.GetString("LEAVINGDATE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I do not understand. Please enter the date or time for your booking..
        /// </summary>
        public static string NOT_RECOGNIZED_DATE {
            get {
                return ResourceManager.GetString("NOT_RECOGNIZED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many people should we expect?.
        /// </summary>
        public static string NUMBEROFPEOPLE_PROMPT {
            get {
                return ResourceManager.GetString("NUMBEROFPEOPLE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many people are you bringing?.
        /// </summary>
        public static string NUMBEROFPEOPLE_REPROMPT {
            get {
                return ResourceManager.GetString("NUMBEROFPEOPLE_REPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PERSON {
            get {
                return ResourceManager.GetString("PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚬.
        /// </summary>
        public static string SMOKING_ALLOWED {
            get {
                return ResourceManager.GetString("SMOKING_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚭.
        /// </summary>
        public static string SMOKING_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("SMOKING_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need a specific day to help you..
        /// </summary>
        public static string SPECIFICTIME_REPLY {
            get {
                return ResourceManager.GetString("SPECIFICTIME_REPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are looking for a room for {0} people between {1} and {2}. Is this correct?.
        /// </summary>
        public static string STATE_OVERVIEW {
            get {
                return ResourceManager.GetString("STATE_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your arrival date to {0}?.
        /// </summary>
        public static string UPDATE_ARRIVALDATE_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_ARRIVALDATE_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your arrival date?.
        /// </summary>
        public static string UPDATE_ARRIVALDATE_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_ARRIVALDATE_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your email to {0}?.
        /// </summary>
        public static string UPDATE_EMAIL_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_EMAIL_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update your email address? .
        /// </summary>
        public static string UPDATE_EMAIL_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_EMAIL_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your leaving date to {0}?.
        /// </summary>
        public static string UPDATE_LEAVINGDATE_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_LEAVINGDATE_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your leaving date?.
        /// </summary>
        public static string UPDATE_LEAVINGDATE_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_LEAVINGDATE_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the number of people to {0}?.
        /// </summary>
        public static string UPDATE_NUMBEROFPEOPLE_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_NUMBEROFPEOPLE_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do want to change the number of people?.
        /// </summary>
        public static string UPDATE_NUMBEROFPEOPLE_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_NUMBEROFPEOPLE_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♿.
        /// </summary>
        public static string WHEELCHAIR_ACCESSIBLE {
            get {
                return ResourceManager.GetString("WHEELCHAIR_ACCESSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WHEELCHAIR_INACCESIBLE {
            get {
                return ResourceManager.GetString("WHEELCHAIR_INACCESIBLE", resourceCulture);
            }
        }
    }
}
