//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.FetchAvailableRooms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FetchAvailableRoomsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FetchAvailableRoomsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.FetchAvailableRooms.Resources.FetchAvailableRoomsStrings", typeof(FetchAvailableRoomsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the buttons in the card to continue. I can search for rooms again if you would like. .
        /// </summary>
        public static string CONTINUE_OR_UPDATE {
            get {
                return ResourceManager.GetString("CONTINUE_OR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can help you find a room. If you make a mistake try asking me to change it. I can understand sentences like &quot;Can you change my arrival date to next week thursday&quot;. You can do something else by asking me to cancel. .
        /// </summary>
        public static string HELP_MESSAGE {
            get {
                return ResourceManager.GetString("HELP_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry you cannot book a room in the past. .
        /// </summary>
        public static string INCORRECT_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To help you find a room, I will need some information from you. If you make a mistake, ask me to change it for you or use the suggested actions..
        /// </summary>
        public static string INTRODUCTION {
            get {
                return ResourceManager.GetString("INTRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you make a mistake, ask me to change it for you or use the suggested actions. Let&apos;s start..
        /// </summary>
        public static string INTRODUCTION_MORE_INFO {
            get {
                return ResourceManager.GetString("INTRODUCTION_MORE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, let&apos;s start!.
        /// </summary>
        public static string INTRODUCTION_START {
            get {
                return ResourceManager.GetString("INTRODUCTION_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you be leaving?.
        /// </summary>
        public static string LEAVINGDATE_PROMPT {
            get {
                return ResourceManager.GetString("LEAVINGDATE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I do not understand. Please enter the date or time for your booking..
        /// </summary>
        public static string NOT_RECOGNIZED_DATE {
            get {
                return ResourceManager.GetString("NOT_RECOGNIZED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I kept your last search. You were looking for a room for {0} people between {1} and {2}. Is this still what you are looking for?.
        /// </summary>
        public static string REROUTED_STATE_OVERVIEW {
            get {
                return ResourceManager.GetString("REROUTED_STATE_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚬.
        /// </summary>
        public static string SMOKING_ALLOWED {
            get {
                return ResourceManager.GetString("SMOKING_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚭.
        /// </summary>
        public static string SMOKING_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("SMOKING_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need a specific day to help you..
        /// </summary>
        public static string SPECIFICTIME_REPLY {
            get {
                return ResourceManager.GetString("SPECIFICTIME_REPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are looking for a room for {0} people between {1} and {2}. Is this correct?.
        /// </summary>
        public static string STATE_OVERVIEW {
            get {
                return ResourceManager.GetString("STATE_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your arrival date to {0}?.
        /// </summary>
        public static string UPDATE_ARRIVALDATE_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_ARRIVALDATE_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your arrival date?.
        /// </summary>
        public static string UPDATE_ARRIVALDATE_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_ARRIVALDATE_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your email to {0}?.
        /// </summary>
        public static string UPDATE_EMAIL_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_EMAIL_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update your email address? .
        /// </summary>
        public static string UPDATE_EMAIL_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_EMAIL_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your leaving date to {0}?.
        /// </summary>
        public static string UPDATE_LEAVINGDATE_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_LEAVINGDATE_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your leaving date?.
        /// </summary>
        public static string UPDATE_LEAVINGDATE_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_LEAVINGDATE_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the number of people to {0}?.
        /// </summary>
        public static string UPDATE_NUMBEROFPEOPLE_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_NUMBEROFPEOPLE_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do want to change the number of people?.
        /// </summary>
        public static string UPDATE_NUMBEROFPEOPLE_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_NUMBEROFPEOPLE_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to change?.
        /// </summary>
        public static string UPDATE_PROMPT {
            get {
                return ResourceManager.GetString("UPDATE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update something or start a new search?.
        /// </summary>
        public static string UPDATE_SAVED_STATE {
            get {
                return ResourceManager.GetString("UPDATE_SAVED_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♿.
        /// </summary>
        public static string WHEELCHAIR_ACCESSIBLE {
            get {
                return ResourceManager.GetString("WHEELCHAIR_ACCESSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WHEELCHAIR_INACCESIBLE {
            get {
                return ResourceManager.GetString("WHEELCHAIR_INACCESIBLE", resourceCulture);
            }
        }
    }
}
