//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.FetchAvailableRooms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FetchAvailableRoomsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FetchAvailableRoomsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.FetchAvailableRooms.Resources.FetchAvailableRoomsStrings", typeof(FetchAvailableRoomsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last time you were looking for a room for {0} people between {1} and {2}. Is this still what you are looking for?.
        /// </summary>
        public static string CACHED_STATE_OVERVIEW {
            get {
                return ResourceManager.GetString("CACHED_STATE_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, I found {0} rooms for you. .
        /// </summary>
        public static string FOUND_ROOMS {
            get {
                return ResourceManager.GetString("FOUND_ROOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold on, I&apos;m checking... .
        /// </summary>
        public static string HOLD_ON_CHECKING {
            get {
                return ResourceManager.GetString("HOLD_ON_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry you cannot book a room in the past. .
        /// </summary>
        public static string INCORRECT_DATE {
            get {
                return ResourceManager.GetString("INCORRECT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can look up rooms but I need more info. If you make a mistake during our talk, just act natural and ask me to change it. I&apos;ll understand 🧐.
        /// </summary>
        public static string INTRODUCTION_MISTAKES {
            get {
                return ResourceManager.GetString("INTRODUCTION_MISTAKES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can lookup rooms but I need a bit more info. .
        /// </summary>
        public static string INTRODUCTION_MORE_INFO {
            get {
                return ResourceManager.GetString("INTRODUCTION_MORE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, let&apos;s find you a room! 👊.
        /// </summary>
        public static string INTRODUCTION_START {
            get {
                return ResourceManager.GetString("INTRODUCTION_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you be leaving?.
        /// </summary>
        public static string LEAVINGDATE_PROMPT {
            get {
                return ResourceManager.GetString("LEAVINGDATE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I do not understand. Please enter the date or time for your booking..
        /// </summary>
        public static string NOT_RECOGNIZED_DATE {
            get {
                return ResourceManager.GetString("NOT_RECOGNIZED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚬.
        /// </summary>
        public static string SMOKING_ALLOWED {
            get {
                return ResourceManager.GetString("SMOKING_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚭.
        /// </summary>
        public static string SMOKING_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("SMOKING_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, let&apos;s start over..
        /// </summary>
        public static string START_OVER {
            get {
                return ResourceManager.GetString("START_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want a room for {0} people between {1} and {2} right? .
        /// </summary>
        public static string STATE_OVERVIEW {
            get {
                return ResourceManager.GetString("STATE_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: if I ask you when you would leave, you can still change your checkin time by saying &quot;I want to change my checkin time&quot;..
        /// </summary>
        public static string UNDERSTAND_EXAMPLE {
            get {
                return ResourceManager.GetString("UNDERSTAND_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can understand most sentences related to finding a room, such as &quot;I want to checkout next week sunday&quot; and so on..
        /// </summary>
        public static string UNDERSTAND_NLU {
            get {
                return ResourceManager.GetString("UNDERSTAND_NLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your checkin date to {0}?.
        /// </summary>
        public static string UPDATE_ARRIVALDATE_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_ARRIVALDATE_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your checkin date?.
        /// </summary>
        public static string UPDATE_ARRIVALDATE_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_ARRIVALDATE_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your checkout date to {0}?.
        /// </summary>
        public static string UPDATE_LEAVINGDATE_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_LEAVINGDATE_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change your checkout date?.
        /// </summary>
        public static string UPDATE_LEAVINGDATE_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_LEAVINGDATE_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the number of people to {0}?.
        /// </summary>
        public static string UPDATE_NUMBEROFPEOPLE_WITH_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_NUMBEROFPEOPLE_WITH_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do want to change the number of people?.
        /// </summary>
        public static string UPDATE_NUMBEROFPEOPLE_WITHOUT_ENTITY {
            get {
                return ResourceManager.GetString("UPDATE_NUMBEROFPEOPLE_WITHOUT_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to change?.
        /// </summary>
        public static string UPDATE_PROMPT {
            get {
                return ResourceManager.GetString("UPDATE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♿.
        /// </summary>
        public static string WHEELCHAIR_ACCESSIBLE {
            get {
                return ResourceManager.GetString("WHEELCHAIR_ACCESSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WHEELCHAIR_INACCESIBLE {
            get {
                return ResourceManager.GetString("WHEELCHAIR_INACCESIBLE", resourceCulture);
            }
        }
    }
}
