//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.ConfirmOrder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfirmOrderStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfirmOrderStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.ConfirmOrder.Resources.ConfirmOrderStrings", typeof(ConfirmOrderStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just need your phone number in case of an emergency..
        /// </summary>
        public static string ASK_NUMBER {
            get {
                return ResourceManager.GetString("ASK_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we can&apos;t confirm that for you, you have no rooms in your order..
        /// </summary>
        public static string CANNOT_CONFIRM_NO_ROOMS {
            get {
                return ResourceManager.GetString("CANNOT_CONFIRM_NO_ROOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete your order we need some personal information. What name should we use to confirm this booking?.
        /// </summary>
        public static string FULL_NAME_QUICK_REPLY_TEXT {
            get {
                return ResourceManager.GetString("FULL_NAME_QUICK_REPLY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete your order we need your personal information..
        /// </summary>
        public static string INTRO {
            get {
                return ResourceManager.GetString("INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap pay to complete your booking with us 🤑.
        /// </summary>
        public static string TAP_PAY_TO_COMPLETE {
            get {
                return ResourceManager.GetString("TAP_PAY_TO_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, here is your final overview..
        /// </summary>
        public static string THANKS_INFORMATION {
            get {
                return ResourceManager.GetString("THANKS_INFORMATION", resourceCulture);
            }
        }
    }
}
