//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.Prompts.NumberOfPeople.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NumberOfPeopleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumberOfPeopleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.Prompts.NumberOfPeople.Resources.NumberOfPeopleStrings", typeof(NumberOfPeopleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, {0} people would be staying in this room..
        /// </summary>
        public static string HAVE_NUMBER_OF_PEOPLE {
            get {
                return ResourceManager.GetString("HAVE_NUMBER_OF_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I changed the number of people to {0}..
        /// </summary>
        public static string HAVE_UPDATED_NUMBER_OF_PEOPLE {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_NUMBER_OF_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many people would stay in this room?.
        /// </summary>
        public static string NUMBER_OF_PEOPLE_PROMPT {
            get {
                return ResourceManager.GetString("NUMBER_OF_PEOPLE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I didn&apos;t understand. How many people would you bring?.
        /// </summary>
        public static string RETRY_NUMBER_OF_PEOPLE_PROMPT_1 {
            get {
                return ResourceManager.GetString("RETRY_NUMBER_OF_PEOPLE_PROMPT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t understand, how many people would you bring?.
        /// </summary>
        public static string RETRY_NUMBER_OF_PEOPLE_PROMPT_2 {
            get {
                return ResourceManager.GetString("RETRY_NUMBER_OF_PEOPLE_PROMPT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t understand that, how many people would you bring?.
        /// </summary>
        public static string RETRY_NUMBER_OF_PEOPLE_PROMPT_3 {
            get {
                return ResourceManager.GetString("RETRY_NUMBER_OF_PEOPLE_PROMPT_3", resourceCulture);
            }
        }
    }
}
