//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.Prompts.ContinueOrUpdatePrompt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContinueOrUpdatePromptStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContinueOrUpdatePromptStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.Prompts.ContinueOrUpdatePrompt.Resources.ContinueOrUpdatePromptS" +
                            "trings", typeof(ContinueOrUpdatePromptStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a button to continue 👆.
        /// </summary>
        public static string RANDOM_CONTINUE_1 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more info or book by tapping a button 👆.
        /// </summary>
        public static string RANDOM_CONTINUE_2 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue by tapping ☝️.
        /// </summary>
        public static string RANDOM_CONTINUE_3 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can book or view more info by tapping a button 👆.
        /// </summary>
        public static string RANDOM_CONTINUE_4 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a button in one of the cards above to continue ☝️.
        /// </summary>
        public static string RANDOM_CONTINUE_5 {
            get {
                return ResourceManager.GetString("RANDOM_CONTINUE_5", resourceCulture);
            }
        }
    }
}
