//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.BookARoom.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BookARoomStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookARoomStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.BookARoom.Resources.BookARoomStrings", typeof(BookARoomStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you arrive?.
        /// </summary>
        public static string ARRIVALDATE_PROMPT {
            get {
                return ResourceManager.GetString("ARRIVALDATE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your email?.
        /// </summary>
        public static string EMAIL_PROMPT {
            get {
                return ResourceManager.GetString("EMAIL_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for booking with us. To enter payment follow this link:.
        /// </summary>
        public static string FINISHEDBOOKAROOM {
            get {
                return ResourceManager.GetString("FINISHEDBOOKAROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, you would like to arrive on {0}..
        /// </summary>
        public static string HAVE_ARRIVALDATE {
            get {
                return ResourceManager.GetString("HAVE_ARRIVALDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it, I&apos;ve added {0} as your primary contact address..
        /// </summary>
        public static string HAVE_EMAIL {
            get {
                return ResourceManager.GetString("HAVE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving at {0}..
        /// </summary>
        public static string HAVE_LEAVINGDATE {
            get {
                return ResourceManager.GetString("HAVE_LEAVINGDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are bringing {0} people..
        /// </summary>
        public static string HAVE_NUMBEROFPEOPLE {
            get {
                return ResourceManager.GetString("HAVE_NUMBEROFPEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you be leaving?.
        /// </summary>
        public static string LEAVINGDATE_PROMPT {
            get {
                return ResourceManager.GetString("LEAVINGDATE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many people should we expect?.
        /// </summary>
        public static string NUMBEROFPEOPLE_PROMPT {
            get {
                return ResourceManager.GetString("NUMBEROFPEOPLE_PROMPT", resourceCulture);
            }
        }
    }
}
