//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Shared.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FacebookStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FacebookStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Shared.Helpers.Resources.FacebookStrings", typeof(FacebookStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string BUTTON_TITLE_CALL {
            get {
                return ResourceManager.GetString("BUTTON_TITLE_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is our number:.
        /// </summary>
        public static string CALL_MESSAGE_PAYLOAD_TEXT {
            get {
                return ResourceManager.GetString("CALL_MESSAGE_PAYLOAD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to book a room..
        /// </summary>
        public static string CONTEXT_TEXT_BOOK_A_ROOM {
            get {
                return ResourceManager.GetString("CONTEXT_TEXT_BOOK_A_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could I call you?.
        /// </summary>
        public static string CONTEXT_TEXT_CALL_US {
            get {
                return ResourceManager.GetString("CONTEXT_TEXT_CALL_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you located?.
        /// </summary>
        public static string CONTEXT_TEXT_DIRECTIONS {
            get {
                return ResourceManager.GetString("CONTEXT_TEXT_DIRECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        public static string HEROCARD_BUTTON_DIRECTION_TITLE {
            get {
                return ResourceManager.GetString("HEROCARD_BUTTON_DIRECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have found the most efficient route for you..
        /// </summary>
        public static string HEROCARD_REPLY_TEXT_DIRECTION {
            get {
                return ResourceManager.GetString("HEROCARD_REPLY_TEXT_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To what email address could I send a confirmation email?.
        /// </summary>
        public static string QUICK_REPLY_ASK_EMAIL {
            get {
                return ResourceManager.GetString("QUICK_REPLY_ASK_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you send me your location?.
        /// </summary>
        public static string QUICK_REPLY_ASK_LOCATION {
            get {
                return ResourceManager.GetString("QUICK_REPLY_ASK_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need your phone number in case of emergencies. .
        /// </summary>
        public static string QUICK_REPLY_ASK_NUMBER {
            get {
                return ResourceManager.GetString("QUICK_REPLY_ASK_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string QUICK_REPLY_BUTTON_BOOK_A_ROOM {
            get {
                return ResourceManager.GetString("QUICK_REPLY_BUTTON_BOOK_A_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string QUICK_REPLY_BUTTON_CALL {
            get {
                return ResourceManager.GetString("QUICK_REPLY_BUTTON_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string QUICK_REPLY_BUTTON_DIRECTION {
            get {
                return ResourceManager.GetString("QUICK_REPLY_BUTTON_DIRECTION", resourceCulture);
            }
        }
    }
}
