//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.Prompts.ArrivalDate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrivalDateStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrivalDateStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.Prompts.ArrivalDate.Resources.ArrivalDateStrings", typeof(ArrivalDateStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you be checking in?.
        /// </summary>
        public static string ARRIVAL_DATE_PROMPT_1 {
            get {
                return ResourceManager.GetString("ARRIVAL_DATE_PROMPT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you be arriving?.
        /// </summary>
        public static string ARRIVAL_DATE_PROMPT_2 {
            get {
                return ResourceManager.GetString("ARRIVAL_DATE_PROMPT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you checkin?.
        /// </summary>
        public static string ARRIVAL_DATE_PROMPT_3 {
            get {
                return ResourceManager.GetString("ARRIVAL_DATE_PROMPT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you arrive?.
        /// </summary>
        public static string ARRIVAL_DATE_PROMPT_4 {
            get {
                return ResourceManager.GetString("ARRIVAL_DATE_PROMPT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you want to arrive?.
        /// </summary>
        public static string ARRIVAL_DATE_PROMPT_5 {
            get {
                return ResourceManager.GetString("ARRIVAL_DATE_PROMPT_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you like to arrive?.
        /// </summary>
        public static string ARRIVAL_DATE_PROMPT_6 {
            get {
                return ResourceManager.GetString("ARRIVAL_DATE_PROMPT_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you like to checkin?.
        /// </summary>
        public static string ARRIVAL_DATE_PROMPT_7 {
            get {
                return ResourceManager.GetString("ARRIVAL_DATE_PROMPT_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, you would join us on {0}..
        /// </summary>
        public static string HAVE_ARRIVAL_DATE_1 {
            get {
                return ResourceManager.GetString("HAVE_ARRIVAL_DATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok. Joining us on {0} 🙂.
        /// </summary>
        public static string HAVE_ARRIVAL_DATE_2 {
            get {
                return ResourceManager.GetString("HAVE_ARRIVAL_DATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, joining us on {0} 👊.
        /// </summary>
        public static string HAVE_ARRIVAL_DATE_3 {
            get {
                return ResourceManager.GetString("HAVE_ARRIVAL_DATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, checking in on {0}..
        /// </summary>
        public static string HAVE_ARRIVAL_DATE_4 {
            get {
                return ResourceManager.GetString("HAVE_ARRIVAL_DATE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for a room on {0}..
        /// </summary>
        public static string HAVE_ARRIVAL_DATE_5 {
            get {
                return ResourceManager.GetString("HAVE_ARRIVAL_DATE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I updated your checkin to {0}..
        /// </summary>
        public static string HAVE_UPDATED_ARRIVAL_DATE_1 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_ARRIVAL_DATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I updated your arrival to {0} 😉.
        /// </summary>
        public static string HAVE_UPDATED_ARRIVAL_DATE_2 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_ARRIVAL_DATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I changed you checkin to {0} 😉.
        /// </summary>
        public static string HAVE_UPDATED_ARRIVAL_DATE_3 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_ARRIVAL_DATE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated your arrival to {0}..
        /// </summary>
        public static string HAVE_UPDATED_ARRIVAL_DATE_4 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_ARRIVAL_DATE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated checkin to {0}, no problem 😉.
        /// </summary>
        public static string HAVE_UPDATED_ARRIVAL_DATE_5 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_ARRIVAL_DATE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I changed your arrival to {0}..
        /// </summary>
        public static string HAVE_UPDATED_ARRIVAL_DATE_6 {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_ARRIVAL_DATE_6", resourceCulture);
            }
        }
    }
}
