//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBot.Dialogs.Prompts.ArrivalDate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArrivalDateStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrivalDateStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBot.Dialogs.Prompts.ArrivalDate.Resources.ArrivalDateStrings", typeof(ArrivalDateStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you arrive?.
        /// </summary>
        public static string ARRIVAL_DATE_PROMPT {
            get {
                return ResourceManager.GetString("ARRIVAL_DATE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, you would like to arrive on {0}..
        /// </summary>
        public static string HAVE_ARRIVAL_DATE {
            get {
                return ResourceManager.GetString("HAVE_ARRIVAL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I changed your arrival to {0}..
        /// </summary>
        public static string HAVE_UPDATED_ARRIVAL_DATE {
            get {
                return ResourceManager.GetString("HAVE_UPDATED_ARRIVAL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I did not understand. When would you be arriving?.
        /// </summary>
        public static string RETRY_ARRIVAL_DATE_PROMPT_1 {
            get {
                return ResourceManager.GetString("RETRY_ARRIVAL_DATE_PROMPT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, when would you arrive?.
        /// </summary>
        public static string RETRY_ARRIVAL_DATE_PROMPT_2 {
            get {
                return ResourceManager.GetString("RETRY_ARRIVAL_DATE_PROMPT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t understand, when would you want to arrive?.
        /// </summary>
        public static string RETRY_ARRIVAL_DATE_PROMPT_3 {
            get {
                return ResourceManager.GetString("RETRY_ARRIVAL_DATE_PROMPT_3", resourceCulture);
            }
        }
    }
}
